SEC_App/urls.py
from django.urls import path

from . import views

app_name = 'SEC_App'
urlpatterns = [
    path('', views.searchView, name='search'),
    path('analysis/', views.analysis, name='analysis'),
    path('history/', views.history, name='history'),
    path('register/', views.register, name='register')
]

SEC_project/urls.py
from django import urls
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('', include('SEC_App.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

SEC_App/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields.json import JSONField
from django.conf import settings
import re

# Create your models here.
class Request(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=CASCADE)
    keyword = models.TextField()
    presentationkeyword = models.TextField(null=True, default=None)
    period_start = models.DateField(null=True)
    period_end = models.DateField(null=True)
    true_start = models.TextField(null=True)
    true_end = models.TextField(null=True)
    time_start = models.TimeField(null=True) 
    time_end = models.TimeField(null=True)
    rangeOfsearch =  models.IntegerField(choices=[(0,'@ALKAHRABA OR @AlkahrabaCare OR كلمة البحث'),(1,'كلمة البحث فقط')])
    date_time = models.DateTimeField()
    includeAll = models.IntegerField(default=0, choices=[(0, "OR"),(1, "AND")])
    
    """
    ----------
    includeAll mean the tweet contains all the keyword 
    ----------
    The rangeOfsearch mean that the serach will include what:
    0 : keyword only
    1 : @Alkahrba or @AlkahrabaCare
    2 : option 1 & 2
    ----------
    period-start, period_end: specified by the user
    true_start, true_end: from the extracted tweets 
    """
    
class Tweet(models.Model):
    tweet_id = models.TextField()
    date = models.DateTimeField()
    place = models.TextField()
    tweet_text = models.TextField()
    hashtags =models.TextField()
    urls = models.TextField()
    nlike = models.IntegerField()
    nretweet = models.IntegerField()
    nreply = models.IntegerField()
    username = models.TextField()
    name = models.TextField()
    request = models.ForeignKey(Request, on_delete=CASCADE)
   

class Analysis(models.Model):
    request = models.ForeignKey(Request, on_delete=CASCADE)
    tweets_list = models.JSONField()
    classes_dic = models.JSONField(null=True, default=None)
    dtm = models.JSONField()
    reactions = models.JSONField()
    from_date = models.TextField()
    to_date = models.TextField()
    period_data = models.JSONField()
    sentiment_data = models.JSONField()
    num_tweets = models.IntegerField()

SEC_App/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserForm(UserCreationForm):
    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('first_name','last_name', 'username', 'email', 'password1' ,'password2')

SEC_App/views.py
from ast import dump
from re import T
from SEC_App.forms import UserForm
from django.shortcuts import redirect, render
from .models import Analysis, Request
import pandas as pd
from json import dumps, decoder, loads
from django.contrib.auth.decorators import login_required
from .utils import *

def register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            return render(request, 'SEC_App/register.html', {'form': form}) 
    else:
        form = UserForm()
        return render(request, 'SEC_App/register.html', {'form': form})

@login_required
def searchView(request):
    """
    home page / search page
    """
    try:
        req_list = list(Request.objects.filter(user=request.user))
    except:
        req_list = None
    if  req_list != None and len(req_list)>=1:
        return render(request,'SEC_App/search.html', {'query_num': req_list[-1].id})
    else: 
        return render(request,'SEC_App/search.html', {'query_num': None})

@login_required
def analysis(request):
    """
    results and analysis page
    """

    #create request model opject
    req = create_request(request)
    
    #Search for tweets
    try:
        tweets_df = search(req.keyword, limit=request.POST.get('limit',''), 
                            Since = req.period_start, Until = req.period_end)
    except:
        return render(request, 'SEC_App/error.html')

    #save request object
    req.save()
    
    # create and save tweets model objects
    for i, tweet in enumerate(tweets_df):
        req.tweet_set.create(tweet_id=tweets_df.iloc[i].tweet_id, date=tweets_df.iloc[i].date, 
                            place=tweets_df.iloc[i].place, tweet_text=tweets_df.iloc[i].tweet_text, 
                            hashtags=tweets_df.iloc[i].hashtags, urls=tweets_df.iloc[i].urls, 
                            nlike=tweets_df.iloc[i].nlikes, nretweet=tweets_df.iloc[i].nretweets, 
                            nreply=tweets_df.iloc[i].nreplies, username=tweets_df.iloc[i].username, 
                            name=tweets_df.iloc[i].name)
    

    # actual from and to dates
    from_date = tweets_df.iloc[tweets_df.shape[0]-1].date[:10]
    to_date = tweets_df.iloc[0].date[:10]

    req.true_start = from_date
    req.true_end = to_date

    # replace OR & AND with Arabic's for user presentations
    req.presentationkeyword = re.sub('OR','أو',re.sub('AND','و',req.keyword))
    req.save()

    #create requests list object
    try:
        req_list = list(Request.objects.filter(user=request.user))
    except:
        req_list = None

    # *** data preprocessing ***
    #Clean dataframe
    tweets_df_cleaned = cleanDataframe(tweets_df)
    #Clean text
    tweets_df_cleaned_text = tweets_df_cleaned['tweet_text'].apply(lambda text : cleanTxt(text,Emoji_Dict(),stopwords_set()))
    #Preprocessing text: create document term matrix 
    dtm_sentiment = dtm_df(tweets_df_cleaned_text, 'sentiment')
    dtm_topic = dtm_df(tweets_df_cleaned_text, 'topic')
    #(create+show,save:optional) arabic word cloud 
    word_cloud(dtm_topic, path='SEC_App/static/SEC_App/wordcloud.png')

    # *** sentiment and topic predictions ***
    tweets_df_cleaned['sentiment'] = predict_sentiments(dtm_sentiment)
    tweets_df_cleaned['label'] = predict_topic_class(dtm_topic)

    # *** prepare the charts data ****
    reactions = get_reactions_dic(tweets_df_cleaned)
    period_data = get_period_dic(tweets_df_cleaned)
    sentiment_data = get_sentiment_dic(tweets_df_cleaned)
    tweets_dic = get_tweets_dic(tweets_df_cleaned)
    classes_dic = get_classes_dic(tweets_df_cleaned)

    #create analysis object (charts data for faster recreation) 
    req.analysis_set.create(request=req, tweets_list=dumps(tweets_dic), classes_dic=classes_dic, dtm=dtm_topic.to_json(), reactions=reactions, from_date=from_date, 
                            to_date=to_date, period_data=period_data, sentiment_data=sentiment_data, 
                            num_tweets=tweets_df_cleaned.shape[0])

    return render(request, 'SEC_App/results.html',{'tweets_dic': tweets_dic, 'reactions': reactions, 'req': req, 
                                                    'from_date':from_date, 'to_date':to_date, 'period_data':period_data, 
                                                    'sentiment_data':sentiment_data, 'num_tweets':tweets_df_cleaned.shape[0], 
                                                    'req_list':req_list, 'classes_dic': classes_dic})

@login_required
def history(request):
    """
    previous searches/requests page
    """
    #retrieve request model opject
    if request.POST.get('query_num') != None:
        req = Request.objects.get(id=request.POST.get('query_num'))
    else:
        req = Request.objects.get(id=request.GET.get('query_num'))
    
    analysis = Analysis.objects.get(request=req)

    #to decode analysis data
    jsonDec = decoder.JSONDecoder()
    
    #create arabic word cloud 
    word_cloud(pd.read_json(analysis.dtm), path='SEC_App/static/SEC_App/wordcloud.png')

    #create requests list object
    try:
        req_list = list(Request.objects.filter(user=request.user))
    except:
        req_list = None

    return render(request, 'SEC_App/results.html',{'tweets_dic': jsonDec.decode(analysis.tweets_list), 'reactions': analysis.reactions, 'req': req, 
                                                    'from_date':analysis.from_date, 'to_date':analysis.to_date, 'period_data':analysis.period_data, 
                                                    'sentiment_data':analysis.sentiment_data, 'num_tweets':analysis.num_tweets, 
                                                    'req_list':req_list, 'classes_dic': analysis.classes_dic})

SEC_App/templates/SEC_App/error.html
<!DOCTYPE html>
<html lang='ar' dir='rtl'>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'SEC_App/style.css' %}?version=1">

    <!-- Tajawal font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Tajawal&display=swap" rel="stylesheet">

    <title></title>
</head>
<body>
    <div id='error-message'>
    <h2>لا توجد تغريدات ):</h2>
    <h3>حاول تغيير كلمة البحث أو نطاق البحث أو الفترة</h3>
    <br><br>
    <a href="{% url 'SEC_App:search' %}" style="display: block;"><img id='home-button' src="{% static 'SEC_App/home-page.svg' %}" alt="الصفحة الرئيسية" style='display: "inline-block"'></a>
    </div>
</body>
</html>

SEC_App/templates/SEC_App/register.html
<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>تسجيل مستخدم جديد</title>

    {% load static %}
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'SEC_App/style.css' %}?version=3">

    <!-- Tajawal font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Tajawal&display=swap" rel="stylesheet">
</head>
<body>
    <h1 style="text-align: center;">تسجيل مستخدم جديد</h1>
    <fieldset class="input_box" id="register-div">
        {% if form.errors %}
            {{form.errors}}
        {% endif %}
        <form method="POST">
            {% csrf_token %} 
            <!-- {{form.as_p}} -->
            <table class="login-content">
                <tr>
                    <td>الاسم الأول</td>
                    <td><span id='first_name'>{{form.first_name}}</span></td>
                </tr>
                <tr>
                    <td>الاسم الأخير</td>
                    <td><span id='last_name'>{{form.last_name}}</span></td>
                </tr>
                <tr></tr>
                <tr>
                    <td>اسم المستخدم</td>
                    <td><span id='username'>{{form.username}}</span></td>
                </tr>
                <tr>
                    <td>البريد الالكتروني</td>
                    <td><span id='email'>{{form.email}}</span></td>
                </tr>
                <tr>
                    <td>كلمة المرور</td>
                    <td><span id='password1'>{{form.password1}}</span></td>
                </tr>
                <tr>
                    <td>كلمة المرور</td>
                    <td><span id='password2'>{{form.password2}}</span></td>
                </tr>
            </table>
            <br><br>
            <button type="submit" value ="Register">إنشاء حساب جديد</button>
        </form> 
    </fieldset>   
</body>
</html>

SEC_App/templates/SEC_App/search.html
<!DOCTYPE html>
<html lang='ar' dir='rtl'>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>تحليل بيانات شركة الكهرباء</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    {% load static %}
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'SEC_App/style.css' %}?version=12">
    <script src="{% static 'SEC_App/search.js' %}?version=9" defer></script>

    <!-- jQuery Datepicker -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $( function() {
          $("#end_period").datepicker();
          $("#period_start").datepicker();
        } );
    </script>

    <!-- dots  -->
    <link href="{% static 'SEC_App/node_modules/three-dots/dist/three-dots.css' %}" rel="stylesheet">

    <!-- Tajawal font -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Tajawal&display=swap" rel="stylesheet">

</head>
<div id='loading-wrapper'>
    <div id='loading-wrapper-dots'><div class="dot-pulse"></div></div>
    <br><br>
</div>
<div id='loading-wrapper-h3'>جمع وتحليل التغريدات</div>
<body>
    <div id='full-page'>
    <h1 id='home-h1' style="display: flex; align-items: center; justify-content: center;">تحليل تغريدات شركة الكهرباء <img id='home-button' src="{% static 'SEC_App/logo-white.png' %}" alt="الصفحة الرئيسية" style='display: "inline-block"; margin-right: 20px; margin-left: 0px;'></h1>
    <div id='user-div' style="text-align: right; margin-top: 100px; margin-left: 15px;">
        <div id="user-info-div" style="display: flex; align-items: center;">
            <img src="{% static 'SEC_App/user.svg' %}?version=2" style="width: 45px;" alt={{ user.get_username }}>
            <span style="font-size: large; margin-right: 5px; margin-top: 6px;">{{ user.get_username }}</span>
        </div>
        <br>
        {% if query_num != None %}
            <a href="{% url 'SEC_App:history' %}?query_num={{ query_num }}"><button class="light-button" style="background-color: aliceblue; color: #121212;">عمليات البحث السابقة</button></a><br><br>
        {% endif %}
        <a href="{% url 'logout'%}?next={{request.path}}"><button class="light-button">تسجيل الخروج</button></a><br>
    </div>
    <div id="input-box-wrapper">
        <fieldset class='input_box'>
            <legend><h2>أساسي</h2></legend>
            <form autocomplete="off" action="{% url 'SEC_App:analysis' %}"  method="post" onSubmit="loadingPage()">
                {% csrf_token %}
                <input autocomplete="false" name="hidden" type="text" style="display:none;">
                <label for='keyword'>كلمات البحث</label>
                <input list="keywords" id="keyword" name="keyword" onkeydown="keywords()" placeholder="مثال: كهرباء فاتورة انقطاع ..." size="37"/>
                <datalist id='keywords'>
                    <option value="كهرباء">
                    <option value="كهرب">
                    <option value="ألواح شمسية">
                </datalist>
                <select name="or_and" id="or_and" style="display: none;">
                    <option value=0>أو</option>
                    <option value=1>و</option>
                </select><br><br>
                
                <label for="domain">نطــاق البحث</label>
                <select name="domain" id="domain">
                    <option value=0 dir="ltr" size="46">وكلمة البحث (@ALKAHRABA أو @AlkahrabaCare)</option>
                    <option value=1 id="keyword_option" size="46" style="display: none;">كلمة البحث فقط</option>
                </select><br><br>
                <button type="submit">حلل</button>
        </fieldset>
    <br>
    
        <fieldset class='input_box'>
            <legend><h2>مخصص</h2></legend>

            <label for="period_start">الفـتـرة من</label>
            <input id="period_start" name="period_start" size="20">
            
            <label for="end_period">إلى </label>
            <input id="end_period" name="end_period" size="20">
            <br><br>
            <label for="start_time">الوقت من</label>
            <input type="time" id="start_time" name="start_time" size="20">
            <label for="end_time">إلى  </label>
            <input type="time" id="end_time" name="end_time" size="20">
            <br><br>
            <label for="limit" id='limit-label'>الحد الأعلى للتغريدات</label>
            <input type="text" value="100" size="20" id='limit' name='limit'>
            </fieldset>
            </div>
        </form>
    </div>
    
</body>
</html>